[package]
name = "nrf24"
version = "0.1.0"
edition = "2021"

[dependencies]
bitfield = "0.17.0"
embedded-hal = "1.0.0"
embedded-hal-bus = "0.1.0"
errors = {path = "../errors"}
nb.workspace = true

[features]
std = []
